### ISSUE TITLE
Http config  issue: 

### ISSUE THREAD

**Issue by ghorofamike** [nodemailer/wildduck-webmail#37]
this is the backtrace of the error when running this app: 

```
/wildduck-webmail/app.js:97
if (config.service.sso.http.enabled) {
                       ^

TypeError: Cannot read property 'http' of undefined
    at Object.<anonymous> (/wildduck/app.js:97:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at db.connect.err (/wildduck/server.js:30:17)
    at Object.module.exports.connect (/wildduck/lib/db.js:10:12)
```

same as what was done in the parent wildduck repo in this fix:  [here](https://github.com/nodemailer/wildduck/commit/3c8f023ee1556017ce268ddd924229f7271baf79) might be needed here too. but its a guess

**Comment by laurivosandi** [comment]
Feel free to submit PR or just keep the `[sso]` section in the config file intact
