### ISSUE TITLE
Logging out results in a 502

### ISSUE THREAD

**Issue by Your-New-SJW-Waifu** [nodemailer/wildduck-webmail#51]
From the logs:

```
Jan  3 18:54:10 fedora wildduck-www[2931694]: /opt/wildduck-webmail/node_modules/passport/lib/http/request.js:65
Jan  3 18:54:10 fedora wildduck-www[2931694]:     if (typeof done != 'function') { throw new Error('req#logout requires a callback function'); }
Jan  3 18:54:10 fedora wildduck-www[2931694]:                                      ^
Jan  3 18:54:10 fedora wildduck-www[2931694]: Error: req#logout requires a callback function
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at IncomingMessage.req.logout.req.logOut (/opt/wildduck-webmail/node_modules/passport/lib/http/request.js:65:44)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at /opt/wildduck-webmail/lib/passport.js:27:17
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at /opt/wildduck-webmail/lib/api-client.js:446:16
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at parseComplete (/opt/wildduck-webmail/node_modules/restify-clients/lib/StringClient.js:357:13)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at parseResponse (/opt/wildduck-webmail/node_modules/restify-clients/lib/JsonClient.js:139:16)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at IncomingMessage._done (/opt/wildduck-webmail/node_modules/restify-clients/lib/StringClient.js:250:16)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at IncomingMessage.f (/opt/wildduck-webmail/node_modules/once/once.js:25:25)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at Object.onceWrapper (events.js:519:28)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at IncomingMessage.emit (events.js:412:35)
Jan  3 18:54:10 fedora wildduck-www[2931694]:     at endReadableNT (internal/streams/readable.js:1333:12)
```

**Comment by carlosang2** [comment]
[Pull request](https://github.com/nodemailer/wildduck-webmail/pull/53)
